spring:
  main:
    banner-mode: "off" # 若想关闭banner 此处并须是"off"  如果是off则会抛异常
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dbname
  redis:
    host: localhost
    port: 6379
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  rsocket:
    server:
      port: 8887
#    password: 123
debug: false
test:
  value: 26
  value2: ${test.value} is a number
server:
  port: 8888
  shutdown: "graceful"
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "env,beans"

resilience4j.retry:
    configs:
      default:
        max-attempts: 2

    instances:
      backend:
        base-config: default
        max-attempts: 2
        wait-duration: 10s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.lang.Exception
          - java.lang.NumberFormatException

resilience4j.ratelimiter:
  instances:
    backendA:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
    backendB:
      limitForPeriod: 6
      limitRefreshPeriod: 500ms
      timeoutDuration: 3s


