GET https://{{ip}}/users/octocat/orgs
Accept: application/json


###
GET https://localhost:9200/
Accept: application/json

###
GET http://localhost:9001/getPrpgroupList?proposalNo=TZDB201932045000004444
Accept: application/json

###