package com.ggggght.learningjava8.leetcode;

/**
 <p>给你一个字符串&nbsp;<code>text</code>，你需要使用 <code>text</code> 中的字母来拼凑尽可能多的单词&nbsp;<strong>&quot;balloon&quot;（气球）</strong>。</p>

 <p>字符串&nbsp;<code>text</code> 中的每个字母最多只能被使用一次。请你返回最多可以拼凑出多少个单词&nbsp;<strong>&quot;balloon&quot;</strong>。</p>

 <p>&nbsp;</p>

 <p><strong>示例 1：</strong></p>

 <p><strong><img alt="" src="https://assets.leetcode-cn.com/aliyun-lc-upload/uploads/2019/09/14/1536_ex1_upd.jpeg" style="height: 35px; width: 154px;"></strong></p>

 <pre><strong>输入：</strong>text = &quot;nlaebolko&quot;
 <strong>输出：</strong>1
 </pre>

 <p><strong>示例 2：</strong></p>

 <p><strong><img alt="" src="https://assets.leetcode-cn.com/aliyun-lc-upload/uploads/2019/09/14/1536_ex2_upd.jpeg" style="height: 35px; width: 233px;"></strong></p>

 <pre><strong>输入：</strong>text = &quot;loonbalxballpoon&quot;
 <strong>输出：</strong>2
 </pre>

 <p><strong>示例 3：</strong></p>

 <pre><strong>输入：</strong>text = &quot;leetcode&quot;
 <strong>输出：</strong>0
 </pre>

 <p>&nbsp;</p>

 <p><strong>提示：</strong></p>

 <ul>
 <li><code>1 &lt;= text.length &lt;= 10^4</code></li>
 <li><code>text</code>&nbsp;全部由小写英文字母组成</li>
 </ul>
 <div><div>Related Topics</div><div><li>哈希表</li><li>字符串</li><li>计数</li></div></div><br><div><li>👍 71</li><li>👎 0</li></div>
 */

public class Leetcode1189 {
  public static void main(String[] args) {
    // System.out.println(maxNumberOfBalloons("nlaebolko"));
    // System.out.println(maxNumberOfBalloons("loonbalxballpoon"));
    // System.out.println(maxNumberOfBalloons("leetcode"));
    // System.out.println(maxNumberOfBalloons("balon"));
    System.out.println(maxNumberOfBalloons("alnaoololonoloalllaloooonbnnnllaboboblaaonlanllnnnoaoolllaobnoooanbooblnlbblllloobooblllnlbabobboooblnllnallllnnobonbonboalolnbnnaoollolaolobllallaoanlolllnnbanboolloooalallonaoolooollonallnbalboaooblnlablbboobonbnllbonboonolloblaollboboonbannnlnnalaalooooolanloobalolnlanboolablaollanlbonaooollaobnnlooanolanonaablboaabnobonllnlllllonlolnblooalalnaonbboaaoaanlolaonlaonboabaaoooaoolbnooblnboobolooloolbooaaoalanbnllbanlonllbaaloololnoobonllobbloblolbbblalolbbooolnbalnnlooaoolnoloobbnoobaoolnnlonnallnanlannlolnaaoblboaolonbnloalbbnlonbnlooaoaoooalolnaaoooonbaaonlonboblbbnaoblololllaoooblolonlnnllooalollaaoooolllollbaaaoablolablolnllbllolblllonobolbalblolanllanoblooobalnaaaonoonnlololbbnoolalloboalllbllolnoolaooallloaooollonnobobaobloaabnanonbolbnooobnboloooonolbobllnbolonnaollollnoblnolaooolnnlloolonblnalaanalllalaaaonoolabolboolnonalaolaolnolnbbnnlalnloblolnlooboloonllnnbnolbonnnanoooolobbnnnbooboolnllolboolobalnlboloonballnallobaoallaoalaoonooonolbloonlaonllblbonolbolanbonalaboloalaloolnaaoooboolonllloonbabboallbnboooallaonlonoboobanbolobnbolloonbloalnbolabanonlaalllolnllbnlnoooonlaballonoonaonaablanonbbblbabobnnbobobboonllnaallanoobalnlonolonnlooooonlbnobonlaolobooalollaoloblaobbonoonlllbblbaanlabonllonollbooaolobalollaollbonnlllooonollnllbolnbonnnolloonaooolobanollolnbolooooalonblanalboloolnanooallooollalnoolbnobloaonloooabnnolnlnaonbooollbboolllaoooallblnollnloannoblbloloaoanllloaaalaloabonolblooolanaollnalalolollbobaolonnlabbooolnbnblooboblooolbnllbolanooloabbnlooaoloaboolbonanlnalbloololoabloalnooolaoolaboboobnoollablaloallonlllnnnallablnaooblboaaaobbonlblablbnoblnbloaoaoanoaollnnnobaoollalllolaaololloolboloanlaaanaonnlnaalollaonoonoolnnlbobaoloobolaloaalblloollalanloobollobllbblboballaooooooooonllnaolnonaablalalnllaallolballnoaolooalllnnboaolabaoboaalbloollllololonobnollblnloaaolaalaoonoaooolalonlllloobbnblaoolaalloaooblnollnnnbbollololaalalloooooallbnabobonblnabalnoaloloooboalolalnlalnolononanooaaalolollooaoollblllbnooblaaaaolbnbnllnnaolbobanboolonlnlonlbnnollnlnoollllboolnbolllabonbnblnnlolllllalallnlooblllolnlloolbllolaolobnlalnolbnblnllbloonnbllnaaaoolobonnoaanllbllbollollnlbnllaballonlalobnlllllnnlbbaonloloobbolboaalblbobllaolloolnlnoooblnalnbaoolanbllaollanoaoboallonbboblablallollllnllnaaloobnbaaobananlnalolaalolooolnalloolnooboobnaoaoolloloblabblobolnnoblnoolboolabonanoaoolalblbnabbobonoolnlnblalnlllalbbllblloonlnoalbloolloaoalloolllnlaallbnlanoanolooallnbobooonbabolooaboaobbloolallboalolllooboolnnllooooloaboonbaaaalnoblloaolannblaaollblllnnaoaololnaobllloooaalnlnlnnnnbloalnbloaonboblboalooanolllbaobnlolnoolloaaoalbnoooloboonbonoolbboolnboonnblaaobbaloabooaabaonnollbboooallanonlblonolnanonnlallbollonallnollnblalolababboollooloalonoollaloonlaaoolalnbnoollboaloonbbblabobobloblololaaononlbaabolaabalnloololllaobobnnnoboboabboolaoonlaannnbaballonlololoobbannolllaoabaaoblnbabaoaalolonanooloblnloooollnbblaloaollboanobolnlnbollooobolaolooaolonnoloallnannbllanlnbnnaollollloloooaolaalobblonablalonanloolllaonnolaobnbabloonloabolbalolnnlllbaobolobllaabooobbnlnanoobolloonobaonnallaoollabablaolnnlllllonllnaalnnnoanbablbllonanlboolaananaalobolaolalnnabolanlnoonbbnbaabnaboololoonaloabonnonbllolnoaloobnnolnbllnlnbnonoalbbllnooooolaoanoonlblbooaoloblblnollaolollbooallollabboonllnbololololnooobalbobablolnbaooaololnnllolababobalallbolabanolooolollolobaobaanlblalaolonbollanooalaooanloaonoaoobolllaooanoloblblabooaloalaallnnnbaollaabonlbbbbabonllollllalllobolbnonoloboalaoononolnonobllaoalooolooblllalbnlolllonllaobboabnaaolllonbnonaoaaalolonlbollnonllbnonllonalnablaaoooloaolbannloobolnolbonbbbllloloboalollabloallaoollooobonoloobbnllnolnbooaolobolobonloaoolbobllooaolbooaalooboababnoalloloalanlnallnnboanonnoonlllllobabllobonllooobobbbbbllblaloblloooablnbbalnaoooonoboobnaoanlonollbbalaaoaobanolnblnnlonnolnoolbnaoblnlaanaolbnollbbllbbalbobbloaooblonnobolnooaollbonnoaooolooloalblloblbonbbnllonbloboloonnnbalbabolaolbonoboaoallbabaobbololabolollollblbboobolbloaobobnlobobolnoolbaaaaaaooanloloannolalooblaloboloolanbaoaoblaoollaoabloaanlllolblbnaloblobonaolnaabaobaolbaalonollaoabaoobooablblbllnnllblnnablalbllbloonnlobbolnlooonalalblalobooonlboooollooooolnaablblnnlbalbllboollloloollooobllaaoolallaoolnaooolalbnloboobaoanlbolllalonoooollaalaoobbloloallloboooooalblnonllolalballlblaonlalonoollnonooolnlolaalaonooboonbbobllanlaaboonalblblnoolllblboobobaolllbnnalaalnloaolllnnboabolnolollblbbnnobabblanbllbolllllaollooallbalabbnnonnonnolbanlnloanlbboollloooooololobboolbanlablllbnbbnoollbbabblnobblbllaalolllllloaolonlolabaonnlolnllooloooonolaloooblonoblnaoobollbnbbllbbanlabaloollnalaalnonloboblnlloonnoollnbblnoolnbnanllbalbolnnaoalolnobllloooolbaonblnoaallonalonoabooblobolboabobabboonaonaabllboaonbbolnlnbbnoaoablaoaaboonoollnollooobonlobolblbnnalbonnloaloolanlabolllonoonolbnlobboloaboloabnlbabooobblnobnnnobllaoaonabbobnlnonloolanlaooblobnlooolbobonnlllblolnooaooobllnnllaobabbonlalolaolooallalonbnlnnllooolbnnlobbooooaaloallbannnnaloolllbaallloolblloonllllnobaoaonllnlaalalonlooooolaonlboblnlololllblblbaolaanbblonaaobnlolaloloboobobnboaaoololllnalnooolbolonnlonnnonlnlnnlbooaooolooblbllnbaoollaoolananbnoalonoooobnblblnobbnbbooanoboonollobllannbolbobbobnllllbnaolnllnalnloboloolblooolbnoblnlloaololonlbllonanoallllalaoolnabllolllaoonlllnobnollalnanallobananolaoolaaolollollaaaolonbanoololbobnloolllloobanoonlbalnlnnablolablabalblnllnoboolonlalbbbloolooobnnoaaoolooloolooabnlalnoabllloonoolobllbblblabaaooalooaoloboboollloaanoooabolonloanlonaaoaooalblbbboonobbbbloallaonbaaaoaloalolaoobolbloboobooolllollnloanbalolnlnlalbalblbolonbnllnolnlnlnooballalllbnlobloloobloanbllnoalollooobllnoboobbnoalalboaoobnnanlllablanalaoolnnalalbllnoobllooooblllbnloallaoobnllnallonlbanllblalbboooalobaobbaobnonlbolonaollllaaolnooaalloolloloobanolllnooollollolbllaobaabololoobooonolboalnllnonlnnlbbooaoaaolnnoaoablbooolobnlnobolnobaalololollnnaoaoollonnlnblolnbnlaooabanaobnlbollaaanoaoaoloobalaoaonnooaolobllbnlollllnlolonbnalnnbnbnolalooalnoolnlblllobolnooonlaabnooaanollbabblnlnlabnnnlalnbooboonnlbnblobnllonoooooobbbnllnboonlollolollooaaololabooabbollonnlalabbnaaoonnaboloonabblalnbooaaboonobaaoaoloolonbaoaooaoolloanaoloolonooalnlollloaolaoaobbaboonlloalalalooloboaloaalnnabblnbolbllnloonabolobnoanlbolnlblbaooolaballoononlonollallbonoblnblnbbolbblonoanbonollolllooooonoblaloooloooaonloboolblnlnnnllbllanaalooonolnllllboblaolobaololloblnooolollbnnoollblbbonannonoonnoobllollllblllbnaaolalnolobanllnlooblooolloolaoooolololooooabnooaoallbboalnanobolbobollanolaollonolbnlanabblllooonaolblnoanooalbbollblloaallblbollllalolllooonbnololoooaonoolaalnblbaboalbnllonooloolllnoaollollnoalanalonabaaoonoollnbonalnloobaoalollnoboonooaoolonblaoalaoollonnnbooaonollollolbllnollalallobloobolaboolololllnblllalnlnlblaooaloblbanallballaboaoaloooaooooonnonolablaonlnolnobaoonnlnlloloanllooooaaoobnoaallboolboloonobaobbnbllooonooonblnooabllnlnblbanlbllooboobaollnoolonaoaololnlllloolnoloblbllallnooolllolonlllblaallobaaoblabnnabnolblaooabobnlloaoaalonaloloaoaaalloollaonnloolaonobaollobbloolollbolbolbbonlabonllnlllobllnanooaaloalnlnboabbaolnlaaollaoobnlloonnnobaoobnlablbbabbboboaolaobollolollolllbllnolllnnlnnlolobllabolbaololoolallalloanoonbnbbnbnllloaoolllloalaoanalonaaolaalllollalboalnboabnbnooolnllaalnnobooblbonlaoloolooobllnblobanoaollobbbaoonalnoolooolnbnnlnlnlbolonoobblnloooolbolloonoblooboboalallllnaolnooallbbonooolbabobonbllobnnlanlnloonobnlonnonnoooobnallobbllonlbbaolaolblalloalnoaaonanabolanoobnoobnoaobnllbonoolnoalabaolobaoanllnolnnaabalooanlaonbolonlaloaalaollllolabblbblnaaoollollbbllabbboblolnoobbllaooobalollllnnboablonaoaloabnabalaaanonnollooooolanbbolalolooooolllnnnonalabnlllobllooblollolnonnblaboololbaloalbnlllnoonllllooalllbbobnbnollanaololbnaalnaloaolnolonlbaolonooloololoaabbnloalbnaoolbaonnonoloooloonlnnnoaolonoooolnnolnnoaloolaolaaooloolbnlabolooooobnoolabloblllnollbloloonaaoaolbaboaoalnboboolobnoaobaaololonlbonlallbaboalllonlooollolabbllolnnlaanbbblnaannbobllbnalnlllnoollalbllolbloonbolballalbbonaoalnalobononolnlnlnollbooaolalonaalnnbbolaobboannannlnoloobonbbnoobollbobollnononbblllnnaallbbnnlalbblllolonolololbnobnllnlnnnolalnooaoaaabnlloablbooblolooobnaoabobnaablalllbnbanllooallolnaolnbbbnlllbonollabnlooanllnbllnolanaollonnnllallobllonlblllllboaboaaboolanlobobloabbnnolnoaoablobllnlaoaonnnbloolllolllolllbnblllblolboooonlnlbbaoallnollblnobaooloooolnalblooolbolbbooooabanlaolnlloolabbalollooolnonlobobllaanllnonloaboaballalnolnnoabnbblboolabnonaoaoblooaooallnabollalbnllloaaaaolonaabooloooaaolllaooobllobllllblnnnloonnboolbalalloabbooaaboanbaaooolloabnnolonolaoaobaaaoolaollllnlllballnolabbonloononlllloolblnlolboloooonbllloollallbloolollnllbobnaoobnoololllollaooalnlnloolbbblonloboooaonbnlllobblllnooaallbnobnoaanloonbbloolnonlboboalalallalollllblllbobobalbllaollllnoolanloblnnlboblnnlaollnllnaaabblalnoallnaonaablbolloblalnlloooonnlolonbblllolnlballooaonllnolbnblloolllolnallooblalllooonbnnbbbananabnoolaaboaloonnalbolbalallalbaonlolononblllnloloboooolllolnlonlaonlloloboollloolblblnlnonnbballlbolaolaoloolllnolooooooonlolblololloolonlonblobnnonnanbbllooolalaaoonbaoaoonlnonnlnbaoooblooolnblnlollnoaloooblblalnonblbaaoabllllbnonalalloaoonllnlnlabaloaooollbonllbooloobablbonbaoooablbaoblonoaolbnbbaabnoolollbabnbalblllnlanboloanllanllobbnoobllolalbolloolllllolaonllllnablollaaloonlloolnblabalolnlolblnoooaolbooalaolaaoboaoobobonnoobllaonanlaballnabonallnalbnnbbaloalnllollnboobllblaaoonblabllblnaobbnloooolalloobolaoobloobablnlnllblolbllbooaonoboloaallllbnoalnblobalonoonnnnabboaolboalolanolllanlnloooabnalnolobolaaaoalnalnlnllbobloanlooaabnnalnblnalbalaboolannolaonoaobnnooonooobbobnlblllbnollalnonobnolaolablnnalaaoonoblbbblnollalnnbaaonllbnolnllalobbolooonnblnooblloonnlobanloblonlollanllllolobbbbooolaanlbaooolalbolobollnaoanooabllooaobloolnbaaloonololaolbllnlbaobllalallllaooobnonanbolnonoolnlabnllbobalaolnbloabaaononaoanalaoooblalbanabonloblooaaboonllonaoanoalobnnoonnlobnllllolnblbalalnolnooblablbololabablllolonboobolnoonbllolallllaonlbaloolnallaoooollnobolaoaaobanlnoobbooloolooolnnaoalnnoobllnlalaoaonlboaooaoooollallollllnalloblbnanlnnonnlloolnnoooobobbbaaoobbolaobnlaaoloooollonloollbnbblaooobollallbbaoooboboanoolaa"));
  }

  public static int maxNumberOfBalloons(String text) {

    char[] chars = text.toCharArray();
    var ans = Integer.MAX_VALUE;

    int[] c = new int[26];
    for (char o : chars) {
      c[o - 'a']++;
    }

    c['l' - 'a'] = Math.floorDiv(c['l' - 'a'],2);
    c['o' - 'a'] = Math.floorDiv(c['o' - 'a'],2);
    var str = "balloon";
    for (char c1 : str.toCharArray()) {
      // if (c1 == 'l' || c1 == 'o') {
      //   if (c[c1 - 'a'] < 2 * ans) {
      //     return 0;
      //   }
      // } else {
      System.out.printf("%s->%d\n",c1,c[c1 - 'a']);
        ans = Math.min(c[c1 - 'a'], ans);
      // }
    }
    return ans;
  }
}
