name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "${{ matrix.root-pom }} on JDK ${{ matrix.java }}"
    strategy:
      matrix:
        java: [ 11 ]
        root-pom: [ 'pom.xml' ]
    runs-on: ubuntu-latest
    env:
      ROOT_POM: ${{ matrix.root-pom }}
    steps:
      - uses: actions/checkout@v3
      # Cancel any previous runs for the same branch that are still running.
      - name: 'Cancel previous runs'
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Checkstyle for Java
        uses: dbelyaev/action-checkstyle@v0.7.4
        with:
          github_token: ${{ github.token }}
          workdir: . # optional, default is .
          level: info # optional, default is info
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD

  generate_docs:
    name: 'Generate latest docs'
    needs: test
    if: github.event_name == 'push' && github.repository == 'google/guava'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3.0.2
      - name: 'Cache local Maven repository'
        uses: actions/cache@v3.0.8
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: 'Generate latest docs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./util/update_snapshot_docs.sh